plugins {
    id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
    id 'maven-publish'
    id 'com.modrinth.minotaur' version '2.8.7'
}
group = project.maven_group
version = project.mod_version

import com.modrinth.minotaur.dependencies.ModDependency

def modrinthToken = file("token.txt").readLines().first

tasks.register("modrinthJar", Jar) {
    archiveClassifier = ""

    dependsOn remapJar
    dependsOn subprojects.collect { it.tasks.named("jar") }

    from sourceSets.main.output

    into("META-INF/jars") {
        from {
            subprojects.collect { project ->
                project.tasks.named("jar").get().archiveFile
            }
        }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

modrinth {
    token = modrinthToken
    projectId = "f7iCBGjv"
    versionNumber = "${version}"
    versionName = "mc${project.minecraft_version}_${project.mod_version}-${project.mod_version_type}.${project.mod_hotfix}"
    uploadFile = tasks.named("modrinthJar")
    gameVersions = [project.minecraft_version]
    loaders = ['fabric']
    dependencies = [
            new ModDependency('P7dR8mSH', 'required'),
            new ModDependency('9s6osm5g', 'required'),
            new ModDependency('mOgUt4GM', 'required')
    ]
}

base {
    archivesName = project.archives_base_name
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "payload" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

repositories {
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/releases/" }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        // forRepositories(fg.repository) // Uncomment when using ForgeGradle
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    //mappings loom.officialMojangMappings()
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"

    implementation project(":payload_ui")
    include project(":payload_ui")

    implementation("org.apache.xmlgraphics:batik-transcoder:1.19")
    implementation("org.apache.xmlgraphics:batik-codec:1.19")
    include("org.apache.xmlgraphics:batik-transcoder:1.19")
    include("org.apache.xmlgraphics:batik-codec:1.19")
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}

subprojects {
    apply plugin: 'net.fabricmc.fabric-loom'
    apply plugin: 'maven-publish'

    repositories {
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://maven.terraformersmc.com/releases/" }

        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            // forRepositories(fg.repository) // Uncomment when using ForgeGradle
            filter {
                includeGroup "maven.modrinth"
            }
        }
    }

    dependencies {
        // To change the versions see the gradle.properties file
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
        //mappings loom.officialMojangMappings()
        implementation "net.fabricmc:fabric-loader:${project.loader_version}"

        implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

        implementation "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"
        implementation "com.terraformersmc:modmenu:${project.modmenu_version}"

        implementation("org.apache.xmlgraphics:batik-transcoder:1.19")
        implementation("org.apache.xmlgraphics:batik-codec:1.19")
        include("org.apache.xmlgraphics:batik-transcoder:1.19")
        include("org.apache.xmlgraphics:batik-codec:1.19")
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 25
    }

    java {
        // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
        // if it is present.
        // If you remove this line, sources will not be generated.
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    processResources {
        inputs.property "version", project.version
        inputs.property "minecraft_version", project.minecraft_version
        inputs.property "loader_version", project.loader_version
        filteringCharset "UTF-8"

        filesMatching("fabric.mod.json") {
            expand "version": project.version,
                    "minecraft_version": project.minecraft_version,
                    "loader_version": project.loader_version
        }
    }
}