# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=0.1.0
mod_version_type=beta
mod_hotfix=1
maven_group=midvightmirage
archives_base_name=Payload
# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.158.0+26.2
# Mods
cloth_config_version=26.2.155
modmenu_version=20.0.1